### ISSUE TITLE
Help with proxy

### ISSUE THREAD

**Issue by SuperZombi** [A1ex-N/anime-ai-cli#5]
Can you recommend some free proxy or free hosting server for python?
I'm using [REPL](https://replit.com/) and theirs servers located at US, so this library not working ("service upgrade" error). I was tried many proxies, but no one don't suit ((

**Comment by A1ex-N** [comment]
> Can you recommend some free proxy or free hosting server for python? I'm using [REPL](https://replit.com/) and theirs servers located at US, so this library not working ("service upgrade" error). I was tried many proxies, but no one don't suit ((

I've never used any proxies or server hosting so i can't recommend any.
